name = "cel"
version = "0.2.0"

description = "A CEL (Common Expression Language) parser and interpreter in pure Gleam"
licences = ["Apache-2.0", "MIT"]
repository = { type = "github", user = "JonasHedEng", repo = "cel-gleam" }
# links = [{ title = "Website", href = "" }]

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
# decode = ">= 1.0.0 and < 2.0.0"
# `zero.lazy` available from here: https://github.com/JonasHedEng/decode/tree/lazy-decoder
decode = { path = "../decode" }

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
gleam_json = ">= 2.1.0 and < 3.0.0"

[javascript]
typescript_declarations = true
