name = "cel"
version = "0.3.1"

description = "A CEL (Common Expression Language) parser and interpreter in pure Gleam"
licences = ["Apache-2.0", "MIT"]
repository = { type = "github", user = "JonasHedEng", repo = "cel-gleam" }
# links = [{ title = "Website", href = "" }]

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
decode = ">= 1.0.0 and < 2.0.0"
gleam_yielder = ">= 1.1.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
gleam_json = ">= 2.1.0 and < 3.0.0"

[javascript]
typescript_declarations = true
